app:
  build: .
  ports:
    - "8080:8080"
  links:
    - db:db
  environment:
    APP_PORT: ":8080"
    DB_DRIVER: mysql
    DB_DSN: "root:password@tcp(db)/tax_db"

db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: tax_db
  volumes:
    - ./sql:/docker-entrypoint-initdb.d